import { theme as antdTheme } from "antd";
import type { ConfigProviderProps } from "antd";

export type AntdTheme = NonNullable<ConfigProviderProps["theme"]>;

export type AppTheme = {
  key: string;
  label: string;
  theme: AntdTheme;
};

// ── RetroFlow Dark (Tasarım 1) ───────────────────────────────────────
// Dark-first glassmorphism, Electric Violet primary, Inter font
export const retroflowDarkTheme: AntdTheme = {
  algorithm: antdTheme.darkAlgorithm,
  token: {
    colorPrimary: "#d0bcff",
    colorPrimaryBg: "rgba(208, 188, 255, 0.12)",
    colorPrimaryBgHover: "rgba(208, 188, 255, 0.2)",
    colorPrimaryBorder: "#a078ff",
    colorPrimaryBorderHover: "#d0bcff",
    colorPrimaryHover: "#e9ddff",
    colorPrimaryActive: "#a078ff",
    colorPrimaryText: "#d0bcff",
    colorPrimaryTextHover: "#e9ddff",
    colorPrimaryTextActive: "#a078ff",
    colorSuccess: "#4ade80",
    colorWarning: "#ffb869",
    colorError: "#ffb4ab",
    colorInfo: "#d0bcff",
    colorTextBase: "#e7e0ed",
    colorBgBase: "#15121b",
    colorBgContainer: "rgba(33, 30, 39, 0.85)",
    colorBgElevated: "rgba(44, 40, 50, 0.95)",
    colorBgLayout: "#0f0d15",
    colorBgSpotlight: "rgba(208, 188, 255, 0.15)",
    colorBgMask: "rgba(15, 13, 21, 0.7)",
    colorBorder: "#494454",
    colorBorderSecondary: "#37333d",
    colorText: "#e7e0ed",
    colorTextSecondary: "#cbc3d7",
    colorTextTertiary: "#958ea0",
    colorTextQuaternary: "#494454",
    colorFillSecondary: "rgba(208, 188, 255, 0.06)",
    colorFillTertiary: "rgba(208, 188, 255, 0.03)",
    colorLink: "#d0bcff",
    fontFamily: "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    fontSize: 14,
    fontSizeLG: 16,
    fontSizeHeading1: 48,
    fontSizeHeading2: 32,
    fontSizeHeading3: 20,
    fontSizeHeading4: 16,
    borderRadius: 12,
    borderRadiusSM: 8,
    borderRadiusLG: 16,
    controlHeight: 44,
    controlHeightSM: 32,
    controlHeightLG: 54,
    padding: 16,
    paddingSM: 12,
    paddingLG: 24,
    margin: 16,
    marginSM: 12,
    marginLG: 24,
    boxShadow: "0 8px 24px rgba(208, 188, 255, 0.15)",
    boxShadowSecondary: "0 4px 12px rgba(208, 188, 255, 0.08)",
  },
  components: {
    Button: {
      borderRadius: 9999,
      borderRadiusLG: 9999,
      colorPrimary: "#d0bcff",
      colorPrimaryHover: "#e9ddff",
      colorPrimaryActive: "#a078ff",
      primaryShadow: "0 0 20px rgba(208, 188, 255, 0.35)",
      contentFontSize: 14,
      controlHeight: 44,
      controlHeightLG: 54,
      controlHeightSM: 32,
      paddingInline: 24,
    },
    Card: {
      borderRadiusLG: 12,
      colorBgContainer: "rgba(33, 30, 39, 0.8)",
      colorBorderSecondary: "rgba(255, 255, 255, 0.08)",
      boxShadow: "0 8px 24px rgba(208, 188, 255, 0.1)",
      paddingLG: 24,
    },
    Input: {
      borderRadius: 12,
      activeBorderColor: "#d0bcff",
      activeShadow: "0 0 0 3px rgba(208, 188, 255, 0.2)",
      hoverBorderColor: "#a078ff",
      colorBgContainer: "rgba(33, 30, 39, 0.6)",
      controlHeight: 44,
      controlHeightLG: 54,
      controlHeightSM: 32,
    },
    Select: {
      borderRadius: 12,
      activeBorderColor: "#d0bcff",
      activeOutlineColor: "rgba(208, 188, 255, 0.2)",
      hoverBorderColor: "#a078ff",
      optionSelectedBg: "rgba(208, 188, 255, 0.15)",
      optionSelectedColor: "#e9ddff",
      selectorBg: "rgba(33, 30, 39, 0.6)",
      controlHeight: 44,
    },
    Modal: {
      borderRadiusLG: 16,
      contentBg: "rgba(33, 30, 39, 0.95)",
      headerBg: "rgba(33, 30, 39, 0.95)",
      footerBg: "rgba(33, 30, 39, 0.95)",
      titleFontSize: 20,
    },
    Table: {
      borderColor: "#494454",
      headerBg: "rgba(44, 40, 50, 0.9)",
      headerColor: "#cbc3d7",
      rowHoverBg: "rgba(208, 188, 255, 0.05)",
      cellPaddingBlock: 16,
      cellPaddingInline: 16,
    },
    Menu: {
      itemBg: "transparent",
      itemColor: "#cbc3d7",
      itemHoverBg: "rgba(208, 188, 255, 0.1)",
      itemHoverColor: "#d0bcff",
      itemSelectedBg: "rgba(208, 188, 255, 0.15)",
      itemSelectedColor: "#d0bcff",
      itemBorderRadius: 8,
      itemHeight: 44,
    },
    Alert: {
      borderRadiusLG: 12,
    },
    Badge: {
      colorSuccess: "#4ade80",
      colorError: "#ffb4ab",
      colorWarning: "#ffb869",
    },
    Steps: {
      colorPrimary: "#d0bcff",
    },
    DatePicker: {
      borderRadius: 12,
      activeBorderColor: "#d0bcff",
      activeShadow: "0 0 0 3px rgba(208, 188, 255, 0.2)",
      hoverBorderColor: "#a078ff",
    },
    Tabs: {
      inkBarColor: "#d0bcff",
      itemActiveColor: "#d0bcff",
      itemHoverColor: "#e9ddff",
      itemSelectedColor: "#d0bcff",
    },
  },
};

// ── Luminous Modernist Light (Tasarım 2) ─────────────────────────────
// Light-first, high-contrast, Hanken Grotesk + Manrope fonts
export const luminousLightTheme: AntdTheme = {
  token: {
    colorPrimary: "#6b38d4",
    colorPrimaryBg: "#e9ddff",
    colorPrimaryBgHover: "#d0bcff",
    colorPrimaryBorder: "#a078ff",
    colorPrimaryBorderHover: "#8455ef",
    colorPrimaryHover: "#8455ef",
    colorPrimaryActive: "#5516be",
    colorPrimaryText: "#6b38d4",
    colorPrimaryTextHover: "#5516be",
    colorPrimaryTextActive: "#23005c",
    colorSuccess: "#006c49",
    colorWarning: "#c77c00",
    colorError: "#ba1a1a",
    colorInfo: "#6b38d4",
    colorTextBase: "#131b2e",
    colorBgBase: "#faf8ff",
    colorBgContainer: "#ffffff",
    colorBgElevated: "#ffffff",
    colorBgLayout: "#f2f3ff",
    colorBgSpotlight: "rgba(19, 27, 46, 0.85)",
    colorBgMask: "rgba(19, 27, 46, 0.45)",
    colorBorder: "#cbc3d7",
    colorBorderSecondary: "#dae2fd",
    colorText: "#131b2e",
    colorTextSecondary: "#494454",
    colorTextTertiary: "#7b7486",
    colorTextQuaternary: "#cbc3d7",
    colorFillSecondary: "#eaedff",
    colorFillTertiary: "#f2f3ff",
    colorLink: "#6b38d4",
    fontFamily:
      '"Hanken Grotesk", "Manrope", Inter, -apple-system, BlinkMacSystemFont, sans-serif',
    fontSize: 16,
    fontSizeSM: 14,
    fontSizeLG: 18,
    fontSizeHeading1: 48,
    fontSizeHeading2: 32,
    fontSizeHeading3: 24,
    fontSizeHeading4: 20,
    borderRadius: 12,
    borderRadiusSM: 6,
    borderRadiusLG: 24,
    controlHeight: 44,
    controlHeightSM: 32,
    controlHeightLG: 54,
    padding: 16,
    paddingSM: 12,
    paddingLG: 24,
    margin: 16,
    marginSM: 12,
    marginLG: 24,
    boxShadow: "0 10px 30px -5px rgba(109, 56, 212, 0.1)",
    boxShadowSecondary: "0 4px 12px rgba(109, 56, 212, 0.06)",
  },
  components: {
    Button: {
      borderRadius: 9999,
      borderRadiusLG: 9999,
      colorPrimary: "#6b38d4",
      colorPrimaryHover: "#8455ef",
      colorPrimaryActive: "#5516be",
      primaryShadow: "0 10px 30px -5px rgba(109, 56, 212, 0.25)",
      contentFontSize: 16,
      controlHeight: 44,
      controlHeightLG: 54,
      controlHeightSM: 32,
      paddingInline: 24,
      defaultBg: "#ffffff",
      defaultBorderColor: "#cbc3d7",
      defaultColor: "#131b2e",
      defaultHoverBorderColor: "#6b38d4",
      defaultHoverColor: "#6b38d4",
    },
    Card: {
      borderRadiusLG: 12,
      colorBgContainer: "#ffffff",
      colorBorderSecondary: "#e2e7ff",
      boxShadow: "0 10px 30px -5px rgba(109, 56, 212, 0.08)",
      headerFontSize: 18,
      paddingLG: 24,
    },
    Input: {
      borderRadius: 12,
      activeBorderColor: "#6b38d4",
      activeShadow: "0 0 0 3px rgba(109, 56, 212, 0.12)",
      hoverBorderColor: "#8455ef",
      colorBgContainer: "#ffffff",
      controlHeight: 44,
      controlHeightLG: 54,
      controlHeightSM: 32,
    },
    Select: {
      borderRadius: 12,
      activeBorderColor: "#6b38d4",
      activeOutlineColor: "rgba(109, 56, 212, 0.12)",
      hoverBorderColor: "#8455ef",
      optionSelectedBg: "#e9ddff",
      optionSelectedColor: "#5516be",
      selectorBg: "#ffffff",
      controlHeight: 44,
    },
    Modal: {
      borderRadiusLG: 16,
      contentBg: "#ffffff",
      headerBg: "#ffffff",
      footerBg: "#ffffff",
      titleFontSize: 20,
    },
    Table: {
      borderColor: "#dae2fd",
      headerBg: "#f2f3ff",
      headerColor: "#494454",
      rowHoverBg: "#f5f3ff",
      cellPaddingBlock: 16,
      cellPaddingInline: 16,
      headerBorderRadius: 12,
    },
    Menu: {
      itemBg: "transparent",
      itemColor: "#494454",
      itemHoverBg: "#eaedff",
      itemHoverColor: "#6b38d4",
      itemSelectedBg: "#e9ddff",
      itemSelectedColor: "#5516be",
      itemBorderRadius: 8,
      itemHeight: 44,
    },
    Alert: {
      borderRadiusLG: 12,
      colorSuccessBg: "#d1fae5",
      colorErrorBg: "#ffdad6",
      colorWarningBg: "#fff3cd",
      colorInfoBg: "#e9ddff",
    },
    Badge: {
      colorSuccess: "#006c49",
      colorError: "#ba1a1a",
    },
    Steps: {
      colorPrimary: "#6b38d4",
    },
    DatePicker: {
      borderRadius: 12,
      activeBorderColor: "#6b38d4",
      activeShadow: "0 0 0 3px rgba(109, 56, 212, 0.12)",
      hoverBorderColor: "#8455ef",
    },
    Tabs: {
      inkBarColor: "#6b38d4",
      itemActiveColor: "#6b38d4",
      itemHoverColor: "#8455ef",
      itemSelectedColor: "#6b38d4",
    },
  },
};

export const antdNeonTheme: AntdTheme = {
  token: {
    colorPrimary: "#00E5FF",
    colorPrimaryBg: "#E6FCFF",
    colorPrimaryBgHover: "#B5F5FF",
    colorPrimaryBorder: "#87E8DE",
    colorPrimaryBorderHover: "#36CFC9",
    colorPrimaryHover: "#36F3FF",
    colorPrimaryActive: "#00B8D9",
    colorPrimaryText: "#08979C",
    colorPrimaryTextHover: "#13C2C2",
    colorPrimaryTextActive: "#006D75",
    colorInfo: "#00E5FF",
    colorSuccess: "#52C41A",
    colorWarning: "#FAAD14",
    colorError: "#FF4D4F",
    colorTextBase: "#101828",
    colorBgBase: "#ffffff",
    colorBgContainer: "#ffffff",
    colorBgElevated: "#ffffff",
    colorBgLayout: "#F6FFFE",
    colorBgSpotlight: "#111827",
    colorBorder: "#B5F5EC",
    colorBorderSecondary: "#E6FFFB",
    colorLink: "#08979C",
    colorText: "#101828",
    colorTextSecondary: "#475467",
    colorTextTertiary: "#667085",
    colorTextQuaternary: "#98A2B3",
    colorFillSecondary: "#E6FFFB",
    colorFillTertiary: "#F6FFFE",
    borderRadius: 12,
    borderRadiusSM: 8,
    borderRadiusLG: 16,
    boxShadow: "0 8px 20px rgba(0, 229, 255, 0.18)",
    boxShadowSecondary: "0 18px 40px rgba(0, 229, 255, 0.16)",
  },
  components: {
    Button: {
      borderRadius: 12,
      colorPrimary: "#00E5FF",
      colorPrimaryActive: "#00B8D9",
      colorPrimaryHover: "#36F3FF",
      primaryShadow: "0 8px 20px rgba(0, 229, 255, 0.24)",
      textHoverBg: "#E6FFFB",
    },
    Card: {
      borderRadiusLG: 16,
      boxShadow: "0 8px 20px rgba(0, 229, 255, 0.12)",
      colorBorderSecondary: "#B5F5EC",
    },
    Input: {
      activeBorderColor: "#00B8D9",
      activeShadow: "0 0 0 3px rgba(0, 229, 255, 0.16)",
      borderRadius: 12,
      hoverBorderColor: "#36F3FF",
    },
    Select: {
      activeBorderColor: "#00B8D9",
      activeOutlineColor: "rgba(0, 229, 255, 0.16)",
      borderRadius: 12,
      hoverBorderColor: "#36F3FF",
      optionSelectedBg: "#E6FFFB",
      optionSelectedColor: "#08979C",
    },
  },
};

export const tcellTheme: AntdTheme = {
  token: {
    colorPrimary: "#034EA2",
    colorPrimaryBg: "#DCECFE",
    colorPrimaryBgHover: "#AFD4FE",
    colorPrimaryBorder: "#78B6FD",
    colorPrimaryBorderHover: "#288AFB",
    colorPrimaryHover: "#288AFB",
    colorPrimaryActive: "#023E82",
    colorPrimaryText: "#034EA2",
    colorPrimaryTextHover: "#03438C",
    colorPrimaryTextActive: "#012650",
    colorInfo: "#0A84FF",
    colorSuccess: "#00D665",
    colorWarning: "#FF9500",
    colorError: "#FF3B30",
    colorTextBase: "#253342",
    colorBgBase: "#ffffff",
    colorBgContainer: "#ffffff",
    colorBgElevated: "#ffffff",
    colorBgLayout: "#F5F7F9",
    colorBgSpotlight: "#253342",
    colorBorder: "#E5E7EB",
    colorBorderSecondary: "#F3F4F6",
    colorLink: "#034EA2",
    colorText: "#253342",
    colorTextSecondary: "#4D5761",
    colorTextTertiary: "#6C737F",
    colorTextQuaternary: "#9DA4AE",
    colorFillSecondary: "#F3F4F6",
    colorFillTertiary: "#F9FAFB",
    fontFamily:
      '"Greycliff CF", Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: 16,
    fontSizeSM: 14,
    fontSizeLG: 18,
    fontSizeXL: 20,
    fontSizeHeading1: 48,
    fontSizeHeading2: 40,
    fontSizeHeading3: 32,
    fontSizeHeading4: 24,
    fontSizeHeading5: 20,
    lineHeight: 1.2,
    lineHeightHeading1: 1.2,
    lineHeightHeading2: 1.2,
    lineHeightHeading3: 1.2,
    lineHeightHeading4: 1.2,
    lineHeightHeading5: 1.2,
    controlHeight: 44,
    controlHeightSM: 32,
    controlHeightLG: 54,
    borderRadius: 12,
    borderRadiusSM: 8,
    borderRadiusLG: 16,
    padding: 16,
    paddingSM: 12,
    paddingLG: 24,
    margin: 16,
    marginSM: 12,
    marginLG: 24,
    boxShadow: "0 6px 12px rgba(37, 51, 66, 0.12)",
    boxShadowSecondary: "0 16px 32px rgba(37, 51, 66, 0.14)",
  },
  components: {
    Alert: {
      borderRadiusLG: 16,
      colorErrorBg: "#FFF1F0",
      colorInfoBg: "#DCECFE",
      colorSuccessBg: "#E6FFF2",
      colorWarningBg: "#FFF7E6",
    },
    Badge: {
      borderRadiusSM: 8,
      colorError: "#FF3B30",
      colorInfo: "#0A84FF",
      colorSuccess: "#00D665",
      colorWarning: "#FF9500",
    },
    Button: {
      borderRadius: 12,
      borderRadiusLG: 16,
      colorPrimary: "#034EA2",
      colorPrimaryActive: "#023E82",
      colorPrimaryHover: "#288AFB",
      contentFontSize: 16,
      contentFontSizeLG: 18,
      contentFontSizeSM: 14,
      controlHeight: 44,
      controlHeightLG: 54,
      controlHeightSM: 32,
      defaultBg: "#ffffff",
      defaultBorderColor: "#D2D6DB",
      defaultColor: "#253342",
      defaultHoverBorderColor: "#034EA2",
      defaultHoverColor: "#034EA2",
      paddingInline: 24,
      paddingInlineLG: 28,
      paddingInlineSM: 16,
      primaryShadow: "0 6px 12px rgba(3, 78, 162, 0.18)",
      textHoverBg: "#DCECFE",
    },
    Calendar: {
      borderRadiusLG: 16,
      colorPrimary: "#034EA2",
      fullBg: "#ffffff",
      itemActiveBg: "#DCECFE",
    },
    Card: {
      actionsBg: "#ffffff",
      borderRadiusLG: 16,
      boxShadow: "0 6px 12px rgba(37, 51, 66, 0.12)",
      colorBgContainer: "#ffffff",
      colorBorderSecondary: "#E5E7EB",
      headerBg: "#ffffff",
      headerFontSize: 20,
      paddingLG: 24,
    },
    Checkbox: {
      borderRadiusSM: 8,
      colorPrimary: "#034EA2",
      colorPrimaryHover: "#288AFB",
    },
    Collapse: {
      borderRadiusLG: 16,
      contentBg: "#ffffff",
      headerBg: "#F9FAFB",
    },
    DatePicker: {
      activeBorderColor: "#034EA2",
      activeShadow: "0 0 0 3px rgba(3, 78, 162, 0.12)",
      borderRadius: 12,
      cellActiveWithRangeBg: "#DCECFE",
      cellHoverBg: "#F3F4F6",
      hoverBorderColor: "#288AFB",
    },
    Input: {
      activeBorderColor: "#034EA2",
      activeShadow: "0 0 0 3px rgba(3, 78, 162, 0.12)",
      addonBg: "#F9FAFB",
      borderRadius: 12,
      controlHeight: 44,
      controlHeightLG: 54,
      controlHeightSM: 32,
      errorActiveShadow: "0 0 0 3px rgba(255, 59, 48, 0.12)",
      hoverBorderColor: "#288AFB",
      paddingBlock: 10,
      paddingBlockLG: 14,
      paddingBlockSM: 6,
      paddingInline: 16,
      warningActiveShadow: "0 0 0 3px rgba(255, 149, 0, 0.14)",
    },
    Menu: {
      itemBg: "#ffffff",
      itemBorderRadius: 12,
      itemColor: "#253342",
      itemHeight: 48,
      itemHoverBg: "#DCECFE",
      itemHoverColor: "#034EA2",
      itemSelectedBg: "#DCECFE",
      itemSelectedColor: "#034EA2",
    },
    Modal: {
      borderRadiusLG: 16,
      colorBgElevated: "#ffffff",
      contentBg: "#ffffff",
      footerBg: "#ffffff",
      headerBg: "#ffffff",
      titleFontSize: 24,
      titleLineHeight: 1.2,
    },
    Notification: {
      borderRadiusLG: 16,
      boxShadow: "0 16px 32px rgba(37, 51, 66, 0.14)",
      colorBgElevated: "#ffffff",
    },
    Pagination: {
      borderRadius: 12,
      itemActiveBg: "#034EA2",
      itemActiveColor: "#ffffff",
      itemBg: "#ffffff",
      itemSize: 44,
      itemSizeSM: 40,
    },
    Radio: {
      buttonBg: "#ffffff",
      buttonCheckedBg: "#DCECFE",
      colorPrimary: "#034EA2",
      colorPrimaryHover: "#288AFB",
      dotSize: 10,
      radioSize: 24,
    },
    Select: {
      activeBorderColor: "#034EA2",
      activeOutlineColor: "rgba(3, 78, 162, 0.12)",
      borderRadius: 12,
      controlHeight: 44,
      controlHeightLG: 54,
      controlHeightSM: 32,
      hoverBorderColor: "#288AFB",
      multipleItemBg: "#DCECFE",
      optionActiveBg: "#F3F4F6",
      optionSelectedBg: "#DCECFE",
      optionSelectedColor: "#034EA2",
      optionSelectedFontWeight: 600,
      selectorBg: "#ffffff",
    },
    Switch: {
      colorPrimary: "#034EA2",
      colorPrimaryHover: "#288AFB",
      handleBg: "#ffffff",
      trackHeight: 24,
      trackMinWidth: 44,
      trackPadding: 2,
    },
    Table: {
      borderColor: "#E5E7EB",
      cellPaddingBlock: 16,
      cellPaddingInline: 16,
      headerBg: "#F9FAFB",
      headerBorderRadius: 12,
      headerColor: "#253342",
      rowHoverBg: "#F3F4F6",
    },
    Tabs: {
      horizontalItemPadding: "8px 0",
      inkBarColor: "#034EA2",
      itemActiveColor: "#034EA2",
      itemHoverColor: "#288AFB",
      itemSelectedColor: "#034EA2",
    },
    Tooltip: {
      borderRadius: 8,
      colorBgSpotlight: "#253342",
      colorTextLightSolid: "#ffffff",
    },
  },
};

export const defaultThemeKey = "luminous-light";

export const builtInThemes = [
  {
    key: "luminous-light",
    label: "Luminous Light",
    theme: luminousLightTheme,
  },
  {
    key: "retroflow-dark",
    label: "RetroFlow Dark",
    theme: retroflowDarkTheme,
  },
  {
    key: "antd-neon",
    label: "Ant Design Neon",
    theme: antdNeonTheme,
  },
  {
    key: "tcell",
    label: "Tcell",
    theme: tcellTheme,
  },
] as const satisfies readonly AppTheme[];

export function createThemeOptions(customThemes: readonly AppTheme[] = []) {
  return [...builtInThemes, ...customThemes];
}

export function getThemeByKey(
  themeKey = defaultThemeKey,
  customThemes: readonly AppTheme[] = [],
) {
  return createThemeOptions(customThemes).find((option) => option.key === themeKey)
    ?.theme;
}
